# from contrib.utils import Enum

ESTADO_CIVIL_CHOICES = (
    ('SOLTEIRO', 'SOLTEIRO'),
    ('CASADO', 'CASADO'),
    ('VIUVO', 'VIUVO'),
    ('SEPARADO JUDICIALMENTE', 'SEPARADO JUDICIALMENTE'),
    ('DIVORCIADO', 'DIVORCIADO'),
    ('UNIAO ESTAVEL', 'UNIAO ESTAVEL'),
    ('NAO FOI DEFINIDO NO CADASTRO', 'NÃO FOI DEFINIDO NO CADASTRO'),
)

ATUALIZACAO_STATUS = (
    ('PREENCHENDO', 'PREENCHENDO'),
    ('AGUARDANDO_VALIDACAO', 'AGUARDANDO VALIDAÇÃO'),
    ('RECUSADO', 'RECUSADO'),
    ('ACEITO', 'ACEITO'),
)
