# Generated by Django 2.0.7 on 2018-08-24 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import standard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('numero', models.CharField(max_length=3, unique=True, verbose_name='Número')),
                ('sigla', models.CharField(max_length=6, null=True)),
                ('tem_convenio', models.PositiveIntegerField(choices=[(0, 'NÃO'), (1, 'SIM'), (2, 'DOCUMENTO ELETRÔNICO DE CRÉDITO (DOC)')], null=True, verbose_name='Tem Convênio?')),
                ('numero_convenio', models.CharField(max_length=20, null=True, verbose_name='Número Convênio')),
                ('agencia', models.CharField(max_length=10, null=True, verbose_name='Agência')),
                ('dv_agencia', models.CharField(max_length=2, null=True, verbose_name='DV Agência')),
                ('conta', models.CharField(max_length=20, null=True)),
                ('dv_conta', models.CharField(max_length=2, null=True, verbose_name='DV Conta')),
                ('principal', models.BooleanField(default=False, verbose_name='Banco Principal')),
                ('sequencial_arquivo', models.IntegerField(default=0, verbose_name='Sequencial')),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'verbose_name': 'Banco',
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name='Capacidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'abstract': False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name='Cbo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'abstract': False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name='Circunscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'abstract': False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name='DadoBancario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conta', models.IntegerField(choices=[(1, 'CORRENTE'), (2, 'POUPANÇA'), (3, 'INVESTIMENTO')], verbose_name='Tipo de Conta')),
                ('agencia', models.CharField(max_length=15, verbose_name='Agência com DV')),
                ('conta_corrente_completa', models.CharField(max_length=15, verbose_name='Conta Corrente com DV')),
                ('banco', models.ForeignKey(on_delete=True, to='rh.Banco')),
            ],
            options={
                'verbose_name': 'Dado Bancário',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.IntegerField(choices=[(1, 'TÍTULO DE ELEITOR'), (2, 'CNH'), (3, 'CTPS'), (4, 'PIS/PASEP'), (5, 'NIS'), (7, 'IPSEP'), (8, 'INSS'), (9, 'RESERVISTA'), (10, 'CONSELHO PROFISSIONAL')], verbose_name='Tipo de Documento')),
                ('numero', models.CharField(max_length=30, verbose_name='Número')),
                ('data_expedicao', models.DateField(blank=True, null=True, verbose_name='Data da Expedição')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
            ],
            options={
                'verbose_name': 'Documento',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_endereco', models.CharField(choices=[(1, 'RESIDENCIAL'), (2, 'COMERCIAL'), (3, 'INSTITUCIONAL')], max_length=20, verbose_name='Tipo do Endereço')),
                ('tipo_logradouro', models.CharField(choices=[(8, 'RUA'), (9, 'QUADRA'), (1, 'AVENIDA'), (2, 'PRAÇA'), (3, 'VIELA'), (4, 'PONTO'), (5, 'VIADUTO'), (6, 'ALAMEDA'), (7, 'OUTROS')], max_length=20, verbose_name='Tipo do Logradouro')),
                ('cep', models.CharField(max_length=10, null=True, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=12, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=2000, null=True)),
                ('data_alteracao', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Endereço',
            },
        ),
        migrations.CreateModel(
            name='Entrancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'ordering': ['nome'],
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('sigla', models.CharField(max_length=3, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'ordering': ['nome'],
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2)),
                ('siafi', models.CharField(blank=True, max_length=12, null=True, verbose_name='SIAFI')),
                ('tse', models.CharField(blank=True, max_length=12, null=True, verbose_name='TSE')),
                ('ibge', models.IntegerField(blank=True, null=True, verbose_name='IBGE')),
            ],
            options={
                'verbose_name': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='GrupoComarca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'abstract': False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name='InCapacidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'abstract': False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'ordering': ['nome'],
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name='MesoRegiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'abstract': False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(blank=True, max_length=6, null=True)),
                ('siafi', models.CharField(blank=True, max_length=12, null=True)),
                ('ibge', models.IntegerField(blank=True, null=True, verbose_name='IBGE')),
                ('valor_vale_transporte', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Valor vale transporte')),
            ],
            options={
                'verbose_name': 'Município',
            },
        ),
        migrations.CreateModel(
            name='NecessidadeEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('codigo', models.CharField(max_length=12, null=True, verbose_name='DDI')),
                ('nome_completo', models.CharField(max_length=100, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'verbose_name': 'País',
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Pessoa',
            },
        ),
        migrations.CreateModel(
            name='PessoaFisicaNecessidadeEspecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('necessidadeespecial', models.ForeignKey(blank=True, null=True, on_delete=True, related_name='pessoas_necessidade', to='rh.NecessidadeEspecial', verbose_name='Necessidade Especial')),
            ],
            options={
                'db_table': 'rh_pessoafisica_necessidades_especiais',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('user', models.OneToOneField(on_delete=True, related_name='servidor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_telefone', models.CharField(choices=[('RESIDENCIAL', 'RESIDENCIAL'), ('COMERCIAL', 'COMERCIAL'), ('CELULAR', 'COMERCIAL'), ('FAX', 'FAX'), ('INSTITUCIONAL', 'INSTITUCIONAL')], max_length=20, verbose_name='Tipo de Telefone')),
                ('numero', models.CharField(max_length=15, verbose_name='Número')),
                ('publico', models.BooleanField(default=False, verbose_name='Público')),
                ('data_alteracao', models.DateField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Telefone',
            },
        ),
        migrations.CreateModel(
            name='TipoOrigem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('modified_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
            ],
            options={
                'abstract': False,
            },
            bases=(standard.models.AuditableMixins, models.Model),
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('municipio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rh.Municipio')),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('distancia_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Distância Capital')),
                ('indicador_municipio', models.BooleanField(default=False, verbose_name='Indicador Município')),
                ('sede_termo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Localidade',
            },
            bases=('rh.municipio',),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rh.Pessoa')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=10, null=True, verbose_name='RG')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=1, null=True)),
                ('sangue', models.CharField(blank=True, choices=[('INDEFINIDO', 'INDEFINIDO'), ('AB', 'AB'), ('A', 'A'), ('B', 'B'), ('O', 'O')], default='INDEFINIDO', max_length=40)),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'SOLTEIRO'), ('CASADO', 'CASADO'), ('VIUVO', 'VIUVO'), ('SEPARADO JUDICIALMENTE', 'SEPARADO JUDICIALMENTE'), ('DIVORCIADO', 'DIVORCIADO'), ('UNIAO ESTAVEL', 'UNIAO ESTAVEL'), ('NAO FOI DEFINIDO NO CADASTRO', 'NÃO FOI DEFINIDO NO CADASTRO')], default='NAO DEFINIDO NO CADASTRO', max_length=40)),
                ('raca_cor', models.CharField(choices=[('BRANCA', 'BRANCA'), ('PARDA', 'PARDA'), ('AMARELA', 'AMARELA'), ('NEGRA', 'NEGRA'), ('INDÍGENA', 'INDÍGENA'), ('QUILOMBOLA', 'QUILOMBOLA'), ('NAO INFORMADO', 'NÃO INFORMADO')], max_length=10, verbose_name='Raça/Cor')),
                ('email_pessoal', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_obito', models.DateField(blank=True, null=True, verbose_name='Data Óbito')),
                ('rg_orgao', models.CharField(blank=True, max_length=10, null=True, verbose_name='RG Órgão')),
                ('rg_data_expedicao', models.DateField(blank=True, null=True, verbose_name='RG Data Expedição')),
                ('fator_rh', models.CharField(blank=True, choices=[('INDEFINIDO', 'INDEFINIDO'), ('+', '+'), ('-', '-')], max_length=10, null=True, verbose_name='Fator RH')),
                ('doador', models.BooleanField(default=True, verbose_name='Doador de órgãos')),
                ('nome_pai', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome Pai')),
                ('nome_mae', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome Mãe')),
                ('nome_conjuge', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome Cônjuge')),
                ('necessidade_especial', models.BooleanField(default=False, verbose_name='Necessidade Especial')),
                ('grau_instrucao', models.CharField(blank=True, choices=[('ANALFABETO', 'ANALFABETO'), ('ALFABETIZADO SEM CURSOS REGULARES', 'ALFABETIZADO SEM CURSOS REGULARES'), ('FUNDAMENTAL INCOMPLETO', 'FUNDAMENTAL INCOMPLETO'), ('FUNDAMENTAL COMPLETO', 'FUNDAMENTAL COMPLETO'), ('MÉDIO INCOMPLETO', 'MÉDIO INCOMPLETO'), ('MÉDIO COMPLETO', 'MÉDIO COMPLETO'), ('TÉCNICO', 'TÉCNICO'), ('SUPERIOR INCOMPLETO', 'SUPERIOR INCOMPLETO'), ('SUPERIOR COMPLETO', 'SUPERIOR COMPLETO'), ('ESPECIALIZAÇÃO/PÓS-GRADUAÇÃO', 'ESPECIALIZAÇÃO/PÓS-GRADUAÇÃO'), ('MESTRADO', 'MESTRADO'), ('DOUTORADO', 'DOUTORADO'), ('PÓS-DOUTORADO', 'PÓS-DOUTORADO'), ('INFORMADO', 'INFORMADO')], max_length=40, null=True)),
                ('possui_filhos', models.BooleanField(default=False, verbose_name='Possui filhos')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'ordering': ('nome', 'cpf'),
            },
            bases=('rh.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='dado_bancario',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='dados_bancarios_pessoas', to='rh.DadoBancario', verbose_name='Dado Bancário'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='rh.Endereco', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='rh.Telefone'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='estado',
            field=models.ForeignKey(on_delete=True, to='rh.Estado'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=True, to='rh.Pais', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='documento',
            name='estado_expedicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='rh.Estado', verbose_name='Estado de Expedição'),
        ),
        migrations.AddField(
            model_name='pessoafisicanecessidadeespecial',
            name='pessoafisica',
            field=models.ForeignKey(on_delete=True, related_name='necessidades_pessoa', to='rh.PessoaFisica', verbose_name='Servidor'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='rh.Documento'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='municipio_naturalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='rh.Localidade'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='necessidades_especiais',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='rh.NecessidadeEspecial'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='rg_uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='rh.Estado', verbose_name='RG UF'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='servidor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servidor', to='rh.Servidor', verbose_name='servidor'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=True, to='rh.Localidade'),
        ),
    ]
