# Generated by Django 2.0.7 on 2018-08-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='raca_cor',
            field=models.CharField(choices=[('BRANCA', 'BRANCA'), ('PARDA', 'PARDA'), ('AMARELA', 'AMARELA'), ('NEGRA', 'NEGRA'), ('INDÍGENA', 'INDÍGENA'), ('QUILOMBOLA', 'QUILOMBOLA'), ('NAO INFORMADO', 'NÃO INFORMADO')], max_length=20, verbose_name='Raça/Cor'),
        ),
    ]
