"""
Django settings for recadastramento project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from decouple import config
from unipath import Path

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(config('BASE_FILE', default=__file__)).parent.parent
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_DIR = Path(BASE_DIR).parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@guq01g4ae=a3+8z!g1f#y4t4s*p5a3w!k#7=0bdq1sh2y@=-z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('RECAD_DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['*'] if DEBUG else [config('RECAD_URL')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'bootstrap4',

    'auth',
    'rh',
    'standard',
    'contrib',
    'atualizacao',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'auth.middlewares.EgideAuthenticationMiddleware'
]

ROOT_URLCONF = 'recadastramento.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CONTEXT = "."
CONTEXT_APP = "recadastramento"

WSGI_APPLICATION = 'recadastramento.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# DATABASES = {
# 'default': {
# 'ENGINE': 'django.db.backends.sqlite3',
# 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
# }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME', default='recadastramento1'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASS', default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5436'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Araguaina'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = config('STATIC_ROOT', default=Path(APP_DIR).child('static'))
MEDIA_ROOT = config('MEDIA_ROOT', default=Path(APP_DIR).child('media'))

RECADASTRAMENTO_URL = 'http://localhost:8000'

# Authentication backends
# https://docs.djangoproject.com/en/2.0/topics/auth/customizing/

AUTHENTICATION_BACKENDS = (
    'auth.backends.EgideAuthBackend'
)

# Athenas API
# https://athenas.defensoria.to.def.br/athenas/api/




# Autenticador Egide
# https://egide.defensoria.to.def.br

EGIDE_CLIENT_ID = config('EGIDE_CLIENT_ID')
EGIDE_CLIENT_SECRET = config('EGIDE_CLIENT_SECRET')

EGIDE_URL = 'https://egide.defensoria.to.def.br'
EGIDE_API = '{}/api/v1/me'.format(EGIDE_URL)
EGIDE_REDIRECT_URI = config(
    'EGIDE_REDIRECT_URI',
    default='http://localhost:8000/auth/login/')
EGIDE_AUTHORIZE_URL = config(
    'EGIDE_AUTHORIZE_URL',
    default='{}/oauth/authorize/?client_id={}&response_type=code&redirect_uri={}'.format(
        EGIDE_URL,
        EGIDE_CLIENT_ID,
        EGIDE_REDIRECT_URI))
EGIDE_TOKEN_URL = config(
    'EGIDE_TOKEN_URL', default='{}/oauth/token'.format(EGIDE_URL))
